apiVersion: v1
kind: Service
metadata:
  name: {{ include "msvc-backend.service.name" . }}
  labels:
    {{- include "msvc-backend.labels" . | nindent 4 }}
    tier: backend
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    {{- include "msvc-backend.selectorLabels" . | nindent 4 }}
    tier: backend