{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "msvc-backend.serviceaccount.name" . }}
  labels:
  {{- include "msvc-backend.labels" . | nindent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "msvc-backend.serviceaccount.name" . }}-binding"
  labels:
  {{- include "msvc-backend.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "msvc-backend.serviceaccount.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
  {{- end -}}
