apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "msvc-gateway.defaultName" . }}-secret"
  labels:
  {{- include "msvc-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.secrets.secret }}