apiVersion: v1
kind: Service
metadata:
  name: {{ include "msvc-gateway.defaultName" . }}
  labels:
    {{- include "msvc-gateway.labels" . | nindent 4 }}
    tier: gateway
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "msvc-gateway.selectorLabels" . | nindent 4 }}
